  services:
    app:
      build:
        context: ./php
      container_name: ${APP_SERVICE_NAME}
      working_dir: /var/www
      volumes:
        - ../src:/var/www
      depends_on:
        - ${DB_SERVICE_NAME}
      networks:
        - backend

    nginx:
      image: nginx:latest
      container_name: ${NGINX_SERVICE_NAME}
      ports:
        - "${APP_PORT}:80"
      volumes:
        - ../src:/var/www
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - ${APP_SERVICE_NAME}
      networks:
        - backend

    db:
      image: mysql:8.0
      container_name: ${DB_SERVICE_NAME}
      restart: always
      environment:
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      volumes:
        - db_data:/var/lib/mysql
      networks:
        - backend

volumes:
  db_data:

networks:
  backend:
